name: ZeronNation

# Short description (goes below the title; it will also be used in the RSS feed)
description: Testing.

# Your name, as you want it to appear underneath each post and in the footer
author: TheXeon


# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://yourdomain.com/

markdown: rdiscount
permalink: pretty


exclude: [README.md]

gems:
  - jekyll-sitemap
  - rdiscount